name: 'Terragrunt GitHub Actions'

on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md

env:
  group: null

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@master

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35

    - name: List all changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          case $file in
            vars/lab.tfvars)
              echo "group=lab" >> $GITHUB_ENV
              echo "Detected change in lab environment"
              ;;
            vars/garaza.tfvars)
              echo "group=garaza" >> $GITHUB_ENV
              echo "Detected change in garaza environment"
              ;;
          esac
        done

    - name: Run playbook
      if: ${{ env.group != null }}
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: ./
        options: |
          --extra-vars group=${{ env.group }}
      env:
        LXDREMOTE_PASS: ${{ secrets.LXDREMOTE_PASS }}
